name: 🐛 Bug Feedback (问题反馈)
description: Create a feedback to help us improve (创建一个反馈以帮助我们改进)
title: "🐛 [Bug] "
labels: ["☢️ Bug", "bug"]

body:
  - type: markdown
    attributes:
      value: |
        **Please only use English or Chinese to fill in**
        **请仅使用英文或中文进行填写**
  - type: checkboxes
    id: checks
    attributes:
      label: Before feedback (在反馈之前)
      options:
        - label: I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
          required: true
        - label: The problem can be stably reproduced (这个问题可以被稳定复现)
          required: false
        - label: The problem is generated after upgrading (问题是在升级之后产生的)
          required: false
  - type: dropdown
    id: system
    attributes:
      label: Operating System (操作系统)
      options:
        - Linux
        - MacOS
        - Windows
        - Other
    validations:
      required: true
  - type: dropdown
    id: goversion
    attributes:
      label: Golang Version (Go 版本)
      options:
        - 1.18.x
        - 1.19.x
        - 1.20.x
        - Other
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Goravel Version (Goravel 版本)
      placeholder: 1.12.0
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: Describe The Problem (描述问题)
      value: |
          1. In this environment...
          2. With this config...
          3. Run '...'
          4. See error...
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction Code (复现代码或截图)
      value: |
          ```go
          // Your code here
          ```
    validations:
      required: true
