name: Check PR Title
on:
  workflow_call:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: "^(build|feat|fix|chore|upgrade|refactor|ci|merge|release|revert|perf|style|test)(\\(.+\\))?!?: .+"
          helpMessage: "Your PR title is invalid. Please follow the Conventional Commits specification: https://www.conventionalcommits.org/en/v1.0.0/"
