name: Codecov
on:
  workflow_call:
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests with coverage
        run: go test -timeout 1h -coverprofile="coverage.out" ./...
      - name: Print coverage report
        run: go tool cover -func=coverage.out
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.out
          token: ${{ secrets.CODECOV }}
