name: Test
on:
  workflow_call:
jobs:
  ubuntu:
    strategy:
      matrix:
        go: [ "1.22", "1.23" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests
        run: go test -timeout 1h ./...
  windows:
    strategy:
      matrix:
        go: [ "1.22", "1.23" ]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests
        run: go test -timeout 1h ./...